### ISSUE TITLE
missing debhelper

### ISSUE THREAD

**Issue by didier2020** [giggls/osml10n#17]
for debian install, there was this issue : dpkg-checkbuilddeps: erreur: Unmet build dependencies: debhelper (>= 11).
fix with "apt install debhelper "

**Comment by giggls** [comment]
Hm what do you consider an "issue" here?
I don't get this.
You won't be able to build _any_ Debian package without debhelper.

**Comment by didier2020** [comment]
it is necessary to add in the install.md file that debhelper must be installed (like for python)

**Comment by giggls** [comment]
Not really. The dependency is already documented in [debian/control](../blob/master/debian/control). dpkg-buildpackage would be unable to complain otherwise. Currently dpkg-buildpackage was already telling you about missing dependencies

I really dislike doing redundant stuff like documenting the dependencies from  [debian/control](../blob/master/debian/control) again in [INSTALL.md](../blob/master/INSTALL.md) as this is error-prone.

I documented this for python and lua only because there is no such thing as ``debian/control`` in this case.

I will add a sentence or two about this in [INSTALL.md](../blob/master/INSTALL.md) and close this (non-issue afterwards). If something additional should be documented in this case is that you need to have ``dpkg-dev`` installed.
