### ISSUE TITLE
Osm2pgsql failed due to ERROR: Error loading lua config

### ISSUE THREAD

**Issue by toqeer786** [giggls/osml10n#18]
![osm2pgsql error](https://user-images.githubusercontent.com/115454250/198947951-392bdd91-c176-4dca-93c2-0125383a2301.png)
i have completed all above intsallations steps but whenever i run this command :"osm2pgsql -G -O flex -d osm -S openstreetmap-carto-hstore-only-l10n.lua planet.osm.pbf"
i face an ** ERROR** :
"Osm2pgsql failed due to ERROR: Error loading lua config: error loading module 'osml10n' from file '/usr/local/share/lua/5.2/osml10n.lua':
	/usr/local/share/lua/5.2/osml10n.lua:1: unexpected symbol near char(127)

**Comment by giggls** [comment]
Could it be possible that what happens here is exactly what osm2pgsql tells you?

Either make sure that _openstreetmap-carto-hstore-only-l10n.lua_ is located in the path you are calling osm2pgsql at or specify an absolute or relative path to the file.

Why do people never try to understand error messages?

BTW. Are you aware that calling osm2pgsql this way (in non slim mode) will need a lot of RAM?

Regarding your second "Issue": Did I even talk about a PostgreSQL extension here? If so it would be a bug on my side as there is no such thing anymore.

P.S.: I updated INSTALL.md regarding the required version of osm2pgsql

**Comment by toqeer786** [comment]
Thanks for your response !!!
my question was about osml10n  (Error loading lua config) and i also give the accurate path like this: 
Desktop/osml10n-master$ osm2pgsql -G -O flex -d osm -S openstreetmap-carto-hstore-only-l10n.lua ../openstreetmap-carto-de/data/gcc-states-latest.osm.pbf 
but the error was about lua module please check the error message below 
ERROR message (Osm2pgsql failed due to ERROR: Error loading lua config: openstreetmap-carto-hstore-only-l10n.lua:11: module 'osml10n' not found)....

And one other question i want to add a new extension which is: CREATE EXTENSION osml10n CASCADE;  in postgress, but the error is :
ERROR( could not open extension control file "/usr/share/postgresql/12/extension/osml1on.control": No such file or directory ) i had read the install.md from  (https://github.com/giggls/mapnik-german-l10n/blob/master/INSTALL.md) tell me how can this extension will be installed in my database
kindly help....

**Comment by giggls** [comment]
I have been talking about the path of the lua config file not about your planet dump.

Regarding your second Question: Why do you even think that you will need a PostgreSQL Extension called osml10n?

**Comment by toqeer786** [comment]
my 2nd question was about installtion of https://github.com/giggls/mapnik-german-l10n/blob/master/INSTALL.md project because it need the extension loaded ..

**Comment by giggls** [comment]
Please do not ask questions about the old legacy code in this repository.

**Comment by giggls** [comment]
Again: Why do you even think that you will need a PostgreSQL Extension called osml10n?

**Comment by giggls** [comment]
To hopefully clarify your confusion:

You are referring to the installation instructions of the old legacy code. Why?
This will not help you with installing the new code from this repository.

The instructions for installing the code from this repository are at https://github.com/giggls/osml10n/blob/master/INSTALL.md

If you want to install the old legacy code instead of this one for whatever reason do not open an issue here.

**Comment by toqeer786** [comment]
i want to change maps label to english ,i have a localized osm maps using kosmitk (https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) now i want to change the maps label to english 
please check my map below and tell me how can i change the map labels to english??? 
![Screenshot 2022-10-26 152402](https://user-images.githubusercontent.com/115454250/198002666-a736fb14-894d-4505-bc2e-0f625fb5be37.png)

**Comment by giggls** [comment]
Using the l10n code at this repository along with the a slighty modified style available at https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md will help you to achieve this goal.

Use upstream+l10n branch if you do not want the visual changes from German Style.

However I am still confused why you even tried to install my legacy code from [https://github.com/giggls/mapnik-german-l10n](https://github.com/giggls/mapnik-german-l10n/blob/master/INSTALL.md)

**Comment by Dexolite** [comment]
Hey @giggls , Thanks for the effort creating & supporting this.

As stated by @toqeer786 , we've followed the guide here: https://github.com/giggls/osml10n/blob/master/INSTALL.md
And I can successfully run the geo-transcript-srv.py, and `make test`  returns: 
`87 tests passed, 0 tests failed.`

However I'm still getting the following error:
ERROR: Error loading lua config: /usr/share/osml10n/openstreetmap-carto-hstore-only-l10n.lua:11: module 'osml10n' not found

![image](https://user-images.githubusercontent.com/45750948/200082400-a0854dc0-2a79-484e-993d-830b4cf79b82.png)

After searching for one of the missing files stated here:
`find / -name init.lua`
I've found that it hasn't created the luad module in the correct location,
rather installing it at   /home/USERNAME/osml10n/debian/osml10n/usr/share/lua/5.3/osml10n/
Obviously I've cloned the osml10n repo in the /home/USERNAME/

After copying the module files like so:
`cp -r /home/USERNAME/osml10n/debian/osml10n/usr/share/lua/5.3/osml10n/ /usr/share/lua/5.3/`

I was able to start processing 🥇 

The issue was apparantly calling `make deb` inside /home/USERNAME/osml10n/ caused all sorts of wronged paths, attaching screenshot:

![image](https://user-images.githubusercontent.com/45750948/200084460-28f58447-1b23-46c5-8e34-9567ce1e1bc0.png)

p.s. I've manually fixed the paths so I can run the transcript service and everything else and am now processing.
I'm also trying to get english+local tags displaying on the tiles.
Something else to note, I'm running Overv/openstreetmap-tile-server docker image, and the planet in there is imported in the "gis" database
I've now created a "osm" database with appropriate extensions, and am running the osm2pgsql with openstreetmap-carto-hstore-only-l10n.lua against OSM, hoping that this is the right way. Getting very late here, will get back on this asap

**Comment by giggls** [comment]
Huh? What you are trying to do is absolutely insane.

``make deb``

Will generate a debian package which you have to **install** first!

E.g. like this:

```
dpkg -i osml10n_1.0_all.deb
```

The install paths are not **wrong**.
What's wrong here is the way you are trying to "fix" this.

**Comment by giggls** [comment]
Trying to reproduce this problem I found that you ran the transcription daemon manually.

This way make test will succeed despite the fact that you did not actually **install** the Debian packages.

I wonder if people do actually understand what they are doing.

INSTALL.md is not supposed to be a cooking recipe but a rough explanation about how to get things to work.

**Comment by Dexolite** [comment]
Honestly, I don't understand what is going on here, nor am a developer. Just trying my best to get EN+local names displaying on my map. Spent couple of days going trough everything I can find related. Got to here and by the README.md, I thought what this does is translate the labels ?!

Anyway sorry for wasting your time, the same questioned is being asked everywhere related to renderer/mapnik and no definite answer.

**Comment by giggls** [comment]
The sole purpose of this code here is getting a database which contains latin labels which can be used for rendering. So yes, using this code is part of your answer.

I know that installing this code is not that easy but your statement that there is "no definite answer" is simply wrong.

Sorry to say, but without some basic GNU/Linux knowledge e.g. how to install packages you won't get far. This said, it is no rocket science to install this code either.

P.s.: I am happy to support real issues with this code and the installation instructions.
